---
openapi: 3.0.0

info:
  title: HPC IWM gateway
  description: Access to HPC through firecrest (inside FW through brocker)
  version: 0.1.0
  x-application-name: HPC IWM gateway
  x-oauth-client:
    client-id:
    callback: https://mp-hpc.herokuapp.com/auth_callback
    scopes: ["email", "openid", "profile"]
  x-contacts:
    - jusong.yu@epfl.ch
  x-logo: https://raw.githubusercontent.com/aiidalab/aiidalab-widgets-base/master/miscellaneous/logos/aiidalab.png
  x-products:
    - name: HPC IWM gateway app
      product-id:
      description: HPC IWM gateway app
servers:
  - url: https://staging.materials-marketplace.eu/message-broker

tags:
  - name: System
    description: Provides functionalities for operability of applications.

paths:
  /heartbeat:
    get:
      security:
        - bearerAuth: []
      tags:
        - System
      summary: heartbeat
      description: To check if an application is alive
      operationId: heartbeat
      responses:
        "200":
          description: Success
        "404":
          description: Not found
 
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
