version: '3'

services:

  hpc-gateway:
    restart: always
    depends_on:
      - mongo
    build:
      context: ..
      dockerfile: deploy/base/Dockerfile
      args:
        CONFIG_FILE: config.json
    env_file:
      - ./cscs.env
    volumes:
      - './logs/hpc-gateway:/var/log:delegated'
    ports:
      - '5253:5253'