---
version: '3'

services:

    # the base image of hpc-gateway-app
    base:
        restart: always
        depends_on:
            - mongo
        build:
            context: ..
            dockerfile: deploy/base/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./logs/hpc-gateway:/var/log:delegated
        ports:
            - 5000:5000
        networks:
            - f7t
            - backend

    # marketplace broker
    broker:
        restart: always
        depends_on:
            - base
        build:
            context: ..
            dockerfile: deploy/broker/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./logs/broker:/var/log:delegated
        networks:
            - backend

    mongo:
        restart: always
        image: mongo:4
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

networks:
    f7t:
    # Used to comunicate with f7t deployment
        external: true
    backend:

volumes:
    mongodbdata:
        driver: local
