---
version: '3'

services:

    # the base image of hpc-gateway-app
    base:
        restart: always
        depends_on:
            - mongo
        build:
            context: ..
            dockerfile: deploy/base/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./logs/hpc-gateway:/var/log:delegated
        ports:
            - 5000:5000
        networks:
            # - f7t
            - hpcgw

    # marketplace broker
    broker:
        restart: always
        depends_on:
            - base
        build:
            context: ..
            dockerfile: deploy/broker/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./logs/broker:/var/log:delegated
        networks:
            - hpcgw

    mongo:
        restart: always
        image: mongo:4
        volumes:
            - /home/jyu/gwdb:/data/db
        networks:
            - hpcgw

networks:
    f7t:
        external: true
    hpcgw:
