# this test will create a mp user to real db and create repo to hpc through f7t
import requests
import os
from urllib.parse import urljoin

MP_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHUzMzZGxWQ2hXd2tGVExUS2xrU2VzcGxjUHRCdDlHV3VxM0tHWnduZG5rIn0.eyJleHAiOjE2NTk5NzY5NzEsImlhdCI6MTY1OTk0ODE3MSwiYXV0aF90aW1lIjoxNjU5OTQ4MTcxLCJqdGkiOiJhZjM2NDUwMi05MGM5LTRhOGEtYmU3Zi0wNzE4ZmM4NTBkZDgiLCJpc3MiOiJodHRwczovL3d3dy5tYXRlcmlhbHMtbWFya2V0cGxhY2UuZXUvYXV0aC9yZWFsbXMvbWFya2V0cGxhY2UiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiLCJhY2Nlc3MtY29udHJvbCJdLCJzdWIiOiJlNTdkMDI4MC03YjM4LTQzMGMtYmZlYi0wZDZlOWJmMGUzZTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmcm9udGVuZCIsIm5vbmNlIjoiMjQ1Y2VmMWEtNjcxMS00NWY0LTkwNGQtZDc2MTFmODhlOWM2Iiwic2Vzc2lvbl9zdGF0ZSI6IjVhM2FhMzVmLWE5ZWUtNGI0Yi05ZTE4LTM1OGYzMGJmZDBhNyIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly93d3cubWF0ZXJpYWxzLW1hcmtldHBsYWNlLmV1Il0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLW1hcmtldHBsYWNlIiwib2ZmbGluZV9hY2Nlc3MiLCJhcHAtYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwcC11c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwibWFuYWdlLXVzZXJzIiwibWFuYWdlLWNsaWVudHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwiZnJvbnRlbmQiOnsicm9sZXMiOlsiYWRtaW4iLCJ1c2VyIl19LCJhY2Nlc3MtY29udHJvbCI6eyJyb2xlcyI6WyJhZG1pbiIsInVzZXIiXX19LCJzY29wZSI6Im9wZW5pZCBjbGllbnRfcm9sZXNfZnJvbnRlbmQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjVhM2FhMzVmLWE5ZWUtNGI0Yi05ZTE4LTM1OGYzMGJmZDBhNyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicm9sZXMiOlsiYWRtaW4iLCJ1c2VyIl0sIm5hbWUiOiJKdXNvbmcgWXUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqdXNvbmcueXUiLCJnaXZlbl9uYW1lIjoiSnVzb25nIiwiZmFtaWx5X25hbWUiOiJZdSIsImVtYWlsIjoianVzb25nLnl1QGVwZmwuY2gifQ.eELG4EvHaYJJMnq3UBAVEtHs1ovYj4qbDBFPJY5g9da5yNwkvNZCgN3EdOOTsp5nWm4iMc4A2ZFu7pYDJpNxzBrhv4vVJGC6TkwwV_jeu9Li2CzVJUZVpVMh_-ibxAvSZtgxFbNXeJYXdm8sflMnZ0MPjXc2wIX-MYOjXYm_0OwZJ9Yz9VUDWHtkl9_ZQN64Yddqft4BIb7cNi4iITThUntHv2IYhZ4sKyrfhupI-JxguINUnlAC9Db5EU8JlYolhR4hXngg80VQ6P92lx80CP0nay9umCf4T9MQLvlG7DExd3Jbw-glfNxkZlG2JNfs2vmCLTqAA0PMLNNQYeEpyQ"

HPCGATEWAY_URL="http://127.0.0.1:5253"

headers = {
    "Accept": "application/json",
    "User-Agent": "HPC-app",
    "Authorization": f"Bearer {MP_TOKEN}",
}

rep = requests.get(urljoin(HPCGATEWAY_URL, 'user'), headers=headers)
print(rep.json(), rep)

rep = requests.post(urljoin(HPCGATEWAY_URL, 'user'), headers=headers)
print(rep.json(), rep)