---
name: continuous-integration

on: [push, pull_request]

jobs:

    pre-commit:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
            - uses: pre-commit/action@v2.0.0

    test-package:

        needs: [pre-commit]

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10']

        steps:

            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  submodules: true

            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies for test
              run: pip install -e .[deploy,dev]

            - name: run pytest
              run: pytest -v tests/
              env:
                  F7T_SECRET: ${{ secrets.F7T_SECRET }}
                  F7T_CLIENT_ID: ${{ secrets.F7T_CLIENT_ID }}
